language: php

script:
  - |
    if [ ! -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
      BRANCH=$TRAVIS_PULL_REQUEST_BRANCH
    else
      BRANCH=$TRAVIS_BRANCH
    fi
  - echo "BRANCH - ${BRANCH}"

after_success:
  - | # Master or develop deploy
    if test ${BRANCH} = "master"; then
      echo "Run code"
    fi
